# Generated by Django 6.0.3 on 2026-03-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=100)),
                ('placas', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('nivel_aceite', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('ruido', models.TextField()),
                ('horometro', models.FloatField()),
                ('enfriamiento', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('fecha_prueba', models.DateTimeField()),
                ('estructura', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('oxidacion', models.TextField()),
                ('cableado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('tablero', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('aceite', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('filtro_aceite', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('filtro_aire', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('filtro_combustible', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('escape', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('bateria', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10)),
                ('arranca', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='paneles/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
