# Generated by Django 6.0.3 on 2026-03-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticogenerador',
            name='fecha_prueba',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
