# Generated by Django 6.0.3 on 2026-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_diagnosticogenerador_fecha_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticogenerador',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticogenerador',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
