# Generated by Django 6.0.3 on 2026-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_diagnosticogenerador_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticogenerador',
            name='informacion_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
